"use client";

import { useActionState } from "react";
import { createSubject, type CreateSubjectState } from "./actions";

type PaperOption = { id: string; label: string };
const initialState: CreateSubjectState = { success: false, message: "" };

export function CreateSubjectForm({ papers }: { papers: PaperOption[] }) {
  const [state, formAction, pending] = useActionState(createSubject, initialState);
  return <section className="mt-8 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Add Subject</h2><p className="mt-1 text-sm text-slate-600">Subjects sit inside one Paper. Keep them broad—do not add topic or sub-topic levels.</p><form action={formAction} className="mt-6 grid gap-5 md:grid-cols-2"><label className="block text-sm font-bold md:col-span-2">Paper<select name="paper_id" required defaultValue={papers[0]?.id} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"><option value="">Choose a Paper</option>{papers.map((paper) => <option key={paper.id} value={paper.id}>{paper.label}</option>)}</select></label><label className="block text-sm font-bold">Subject name<input name="name" required defaultValue="Current Affairs" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-bold">Slug<input name="slug" required pattern="[a-z0-9-]+" defaultValue="current-affairs" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-bold md:col-span-2">Description<textarea name="description" rows={3} defaultValue="Regional, National and International Current Affairs" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-bold">Display order<input name="display_order" type="number" min="0" required defaultValue="1" className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="flex items-center gap-3 self-end text-sm font-bold"><input name="is_active" type="checkbox" defaultChecked className="h-4 w-4" />Available to students</label><div className="md:col-span-2"><button disabled={pending || papers.length === 0} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{pending ? "Adding..." : "Add Subject"}</button>{state.message && <p className={`mt-4 text-sm font-semibold ${state.success ? "text-emerald-700" : "text-red-700"}`}>{state.message}</p>}</div></form></section>;
}
