"use client";

import { useActionState, useState } from "react";
import type { Subject } from "@/types/subject";
import { updateSubject, type UpdateSubjectState } from "./actions";
import { SearchableSelect } from "@/components/admin/SearchableSelect";

type PaperOption = { id: string; label: string }; const initialState: UpdateSubjectState = { success: false, message: "" };
export function EditSubjectForm({ subject, papers }: { subject: Subject; papers: PaperOption[] }) {
  const [state, formAction, pending] = useActionState(updateSubject.bind(null, subject.id), initialState); const [paperId, setPaperId] = useState(subject.paper_id);
  return <section className="mt-8 rounded-2xl border bg-white p-6 shadow-sm"><form action={formAction} className="grid gap-5 md:grid-cols-2"><label className="block text-sm font-bold md:col-span-2">Paper<SearchableSelect name="paper_id" value={paperId} onChange={setPaperId} options={papers.map((paper) => ({ value: paper.id, label: paper.label }))} placeholder="Search a Paper" /></label><label className="block text-sm font-bold">Subject name<input name="name" required defaultValue={subject.name} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-bold">Slug<input name="slug" required pattern="[a-z0-9-]+" defaultValue={subject.slug} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-bold md:col-span-2">Description<textarea name="description" rows={3} defaultValue={subject.description ?? ""} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="block text-sm font-bold">Display order<input name="display_order" type="number" min="0" required defaultValue={subject.display_order} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" /></label><label className="flex items-center gap-3 self-end text-sm font-bold"><input name="is_active" type="checkbox" defaultChecked={subject.is_active} className="h-4 w-4" />Available to students</label><div className="md:col-span-2"><button disabled={pending} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{pending ? "Saving..." : "Save Subject"}</button>{state.message && <p className={`mt-4 text-sm font-semibold ${state.success ? "text-emerald-700" : "text-red-700"}`}>{state.message}</p>}</div></form></section>;
}
