import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { PaperForm } from "./PaperForm";
import { DeletePaperButton } from "./DeletePaperButton";

export default async function PapersPage() {
  const supabase = await createClient();
  const [papersResult, groupsResult, categoriesResult] = await Promise.all([supabase.from("papers").select("id, exam_group_id, name, slug, description, duration_minutes, question_count, default_negative_marks, is_active, display_order").order("display_order"), supabase.from("exam_groups").select("id, exam_id, name, display_order").order("display_order"), supabase.from("exams").select("id, name")]);
  const categories = new Map((categoriesResult.data ?? []).map((item) => [item.id, item.name]));
  const groups = groupsResult.data ?? []; const groupLabels = new Map(groups.map((group) => [group.id, `${categories.get(group.exam_id) ?? "Unknown category"} → ${group.name}`]));
  return <main><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-teal-700">Exam structure</p><h1 className="mt-2 text-3xl font-black">Papers</h1><p className="mt-2 text-slate-600">Create the actual government papers under each Exam. Full-length mocks always belong to one Paper.</p></div><PaperForm exams={groups.map((group) => ({ id: group.id, label: groupLabels.get(group.id) ?? group.name }))} />{papersResult.error ? <p className="mt-6 rounded-xl bg-red-50 p-4 text-red-700">{papersResult.error.message}</p> : <section className="mt-8 overflow-hidden rounded-2xl border bg-white"><div className="border-b px-6 py-5"><h2 className="font-bold">Existing Papers</h2></div>{(papersResult.data ?? []).length === 0 ? <p className="p-6 text-sm text-slate-600">No Papers yet. Add the Papers for an Exam before creating Subjects.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Exam</th><th className="px-5 py-3">Paper</th><th className="px-5 py-3">Structure</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{(papersResult.data ?? []).map((paper) => <tr key={paper.id}><td className="px-5 py-4 text-slate-600">{groupLabels.get(paper.exam_group_id) ?? "Unknown Exam"}</td><td className="px-5 py-4"><p className="font-bold">{paper.name}</p><p className="text-xs text-slate-500">{paper.slug}</p></td><td className="px-5 py-4 text-slate-600">{paper.question_count ? `${paper.question_count} questions` : "Question count not set"}{paper.duration_minutes ? ` · ${paper.duration_minutes} min` : ""}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${paper.is_active ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-600"}`}>{paper.is_active ? "Active" : "Inactive"}</span></td><td className="px-5 py-4 text-right"><span className="inline-flex items-center gap-4"><Link href={`/admin/papers/${paper.id}/edit`} className="font-semibold text-teal-700 hover:underline">Edit</Link><DeletePaperButton paperId={paper.id} paperName={paper.name} /></span></td></tr>)}</tbody></table></div>}</section>}</main>;
}
