import Link from "next/link";
import { PublicHeader } from "@/components/site/PublicHeader";
import { createClient } from "@/lib/supabase/server";

type Params = { category?: string; exam?: string; specialization?: string; paper?: string; subject?: string };

export default async function MockTestsPage({ searchParams }: { searchParams: Promise<Params> }) {
  const selected = await searchParams; const supabase = await createClient();
  const [categoriesResult, groupsResult, specializationsResult, papersResult, subjectsResult, testsResult] = await Promise.all([
    supabase.from("exams").select("id, name, description").eq("is_active", true).order("display_order"),
    supabase.from("exam_groups").select("id, exam_id, name, description").eq("is_active", true).order("display_order"),
    supabase.from("exam_specializations").select("id, exam_group_id, name, description").eq("is_active", true).order("display_order"),
    supabase.from("papers").select("id, exam_group_id, specialization_id, name, description, duration_minutes").eq("is_active", true).order("display_order"),
    supabase.from("subjects").select("id, paper_id, name").eq("is_active", true).order("display_order"),
    supabase.from("mock_tests").select("id, paper_id, subject_id, test_scope, title, description, duration_minutes, access_type, price_inr").eq("status", "published").order("display_order"),
  ]);
  const categories = categoriesResult.data ?? []; const groups = groupsResult.data ?? []; const specializations = specializationsResult.data ?? []; const papers = papersResult.data ?? []; const subjects = subjectsResult.data ?? []; const tests = testsResult.data ?? [];
  const category = categories.find((item) => item.id === selected.category);
  const exam = groups.find((item) => item.id === selected.exam && (!category || item.exam_id === category.id));
  const specialization = specializations.find((item) => item.id === selected.specialization && (!exam || item.exam_group_id === exam.id));
  const paper = papers.find((item) => item.id === selected.paper && (!exam || item.exam_group_id === exam.id) && (!specialization || item.specialization_id === specialization.id));
  const subject = subjects.find((item) => item.id === selected.subject && (!paper || item.paper_id === paper.id));
  const href = (values: Params) => `/mock-tests?${new URLSearchParams(Object.entries(values).filter(([, value]) => value).map(([key, value]) => [key, value as string])).toString()}`;
  const crumbs = <div className="mb-7 flex flex-wrap gap-2 text-sm font-semibold text-slate-500"><Link href="/mock-tests" className="hover:text-teal-700">Mock tests</Link>{category && <><span>→</span><Link href={href({ category: category.id })} className="hover:text-teal-700">{category.name}</Link></>}{exam && <><span>→</span><Link href={href({ category: category?.id, exam: exam.id })} className="hover:text-teal-700">{exam.name}</Link></>}{specialization && <><span>→</span><Link href={href({ category: category?.id, exam: exam?.id, specialization: specialization.id })} className="hover:text-teal-700">{specialization.name}</Link></>}{paper && <><span>→</span><Link href={href({ category: category?.id, exam: exam?.id, specialization: specialization?.id, paper: paper.id })} className="hover:text-teal-700">{paper.name}</Link></>}{subject && <><span>→</span><span className="text-slate-900">{subject.name}</span></>}</div>;
  const Card = ({ test }: { test: (typeof tests)[number] }) => <article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-bold">{test.title}</h3><span className={`rounded-full px-3 py-1 text-xs font-bold ${test.access_type === "paid" ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{test.access_type === "paid" ? `₹${test.price_inr}` : "Free"}</span></div><p className="mt-3 min-h-10 text-sm leading-6 text-slate-600">{test.description ?? "A Varadhi practice mock test."}</p><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="text-sm font-semibold text-slate-600">{test.duration_minutes} minutes</span><Link href={`/mock-tests/${test.id}`} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">{test.access_type === "paid" ? "View access" : "Start test"}</Link></div></article>;

  if (!category) return <main className="min-h-screen bg-slate-50"><PublicHeader /><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16"><p className="text-sm font-bold uppercase tracking-[0.15em] text-teal-700">Practice library</p><h1 className="mt-3 text-4xl font-black">Choose your exam category</h1><p className="mt-4 text-slate-600">Start with TGPSC, TET, or any category you add in the admin workspace.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{categories.map((item) => <Link key={item.id} href={href({ category: item.id })} className="rounded-3xl border bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Exam category</p><h2 className="mt-3 text-2xl font-black">{item.name}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{item.description ?? "Browse the available Exams and their Papers."}</p><span className="mt-6 inline-block text-sm font-bold text-teal-700">Choose {item.name} →</span></Link>)}</div></div></main>;

  if (!exam) { const entries = groups.filter((item) => item.exam_id === category.id); return <main className="min-h-screen bg-slate-50"><PublicHeader /><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16">{crumbs}<h1 className="text-4xl font-black">{category.name} Exams</h1><p className="mt-4 text-slate-600">Choose the exam you are preparing for.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{entries.map((item) => <Link key={item.id} href={href({ category: category.id, exam: item.id })} className="rounded-3xl border bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Exam</p><h2 className="mt-3 text-2xl font-black">{item.name}</h2><p className="mt-3 text-sm text-slate-600">{item.description ?? "See Papers and published mock tests."}</p><span className="mt-6 inline-block text-sm font-bold text-teal-700">Continue →</span></Link>)}</div></div></main>; }

  const examSpecializations = specializations.filter((item) => item.exam_group_id === exam.id);
  if (!specialization && examSpecializations.length > 0) return <main className="min-h-screen bg-slate-50"><PublicHeader /><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16">{crumbs}<p className="text-sm font-bold uppercase tracking-[0.15em] text-teal-700">Choose your branch</p><h1 className="mt-3 text-4xl font-black">{exam.name} Specialisations</h1><p className="mt-4 text-slate-600">Choose the engineering branch that matches your recruitment notification.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examSpecializations.map((item) => <Link key={item.id} href={href({ category: category.id, exam: exam.id, specialization: item.id })} className="rounded-3xl border bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Specialisation</p><h2 className="mt-3 text-2xl font-black">{item.name}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{item.description ?? `Papers and mock tests for ${exam.name} ${item.name}.`}</p><span className="mt-6 inline-block text-sm font-bold text-teal-700">View Papers →</span></Link>)}</div></div></main>;

  if (!paper) { const examPapers = papers.filter((item) => item.exam_group_id === exam.id && (specialization ? item.specialization_id === specialization.id : !item.specialization_id)); return <main className="min-h-screen bg-slate-50"><PublicHeader /><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16">{crumbs}<h1 className="text-4xl font-black">{specialization ? `${specialization.name} Papers` : `${exam.name} Papers`}</h1><p className="mt-4 text-slate-600">Each Paper is practised separately, matching the actual exam structure.</p><div className="mt-10 grid gap-5 md:grid-cols-2">{examPapers.map((item) => <Link key={item.id} href={href({ category: category.id, exam: exam.id, specialization: specialization?.id, paper: item.id })} className="rounded-3xl border bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:border-teal-300"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Paper</p><h2 className="mt-3 text-2xl font-black">{item.name}</h2><p className="mt-3 text-sm text-slate-600">{item.description ?? "Full-length and subject-wise practice."}</p>{item.duration_minutes && <p className="mt-4 text-sm font-bold text-slate-500">{item.duration_minutes} minutes</p>}</Link>)}</div>{examPapers.length === 0 && <p className="mt-10 rounded-2xl border border-dashed bg-white p-8 text-slate-600">No Papers are available for this selection yet.</p>}</div></main>; }

  const paperTests = tests.filter((test) => test.paper_id === paper.id && test.test_scope === "paper"); const subjectTests = tests.filter((test) => test.paper_id === paper.id && test.test_scope === "subject");
  if (subject) { const relevant = subjectTests.filter((test) => test.subject_id === subject.id); return <main className="min-h-screen bg-slate-50"><PublicHeader /><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16">{crumbs}<h1 className="text-4xl font-black">{subject.name} Mock Tests</h1><div className="mt-10 grid gap-5 md:grid-cols-2">{relevant.length ? relevant.map((test) => <Card key={test.id} test={test} />) : <p className="rounded-2xl border border-dashed bg-white p-8 text-slate-600">No published {subject.name} tests yet.</p>}</div></div></main>; }
  const activeSubjects = subjects.filter((item) => item.paper_id === paper.id && subjectTests.some((test) => test.subject_id === item.id));
  return <main className="min-h-screen bg-slate-50"><PublicHeader /><div className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16">{crumbs}<h1 className="text-4xl font-black">{paper.name}</h1><p className="mt-4 text-slate-600">Choose a full-length Paper mock or practise a Subject separately.</p>{paperTests.length > 0 && <section className="mt-10"><h2 className="text-2xl font-black">Full-length Mock Tests</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{paperTests.map((test) => <Card key={test.id} test={test} />)}</div></section>}{activeSubjects.length > 0 && <section className="mt-10"><h2 className="text-2xl font-black">Subject-wise Tests</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{activeSubjects.map((item) => <Link key={item.id} href={href({ category: category.id, exam: exam.id, specialization: specialization?.id, paper: paper.id, subject: item.id })} className="rounded-2xl border bg-white p-5 font-bold transition hover:border-teal-300 hover:text-teal-700">{item.name}<span className="mt-2 block text-sm font-semibold text-slate-500">{subjectTests.filter((test) => test.subject_id === item.id).length} mock test(s)</span></Link>)}</div></section>}{paperTests.length === 0 && activeSubjects.length === 0 && <div className="mt-10 rounded-2xl border border-dashed bg-white p-10 text-center text-slate-600">No published tests for this Paper yet.</div>}</div></main>;
}
